api/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views


router = routers.DefaultRouter()
router.register(r'clients', views.ClientAPIView, basename='clients')
router.register(r'mailings', views.MailingAPIView, basename='mailings')

urlpatterns = [
    path('', include(router.urls)),
    path('mailing-report/', views.MailingReportAPIView.as_view()),
    path('mailing-report/<int:mailing_id>/', views.MailingReportAPIView.as_view()),
    path('docs/', views.SchemaView.with_ui('swagger', cache_timeout=0)),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
    path('social_auth/', include('social_django.urls', namespace='social')),
    path('', include('web_ui.urls')),
    path('', include('django_prometheus.urls')),
]

web_ui/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from . import views

app_name = 'web_ui'
urlpatterns = [
    path('', views.MainRedirectView.as_view()),
    path('mailings/', include([
        path('', views.MailingsView.as_view(), name='mailings'),
        path('create/', views.MailingCreateView.as_view(), name='mailing_create'),
        path('<int:mailing_id>/', include([
            path('', views.MailingView.as_view(), name='mailing'),
            path('update/', views.MailingUpdateView.as_view(), name='mailing_update'),
            path('delete/', views.MailingDeleteView.as_view(), name='mailing_delete'),
        ])),
    ])),
    path('mailings-report/', include([
        path('', views.MailingReportView.as_view(), name='mailings_report'),
        path('<int:mailing_id>/', views.MailingReportView.as_view(), name='mailing_report')
    ])),
    path('accounts/', include([
        path('login/', LoginView.as_view(), name='login'),
        path('logout/', LogoutView.as_view(), name='logout'),
    ])),
]

mailing/models.py
from django.db import models

from clients.models import Client
from .constants import DAY_START_TIME, DAY_END_TIME


class Mailing(models.Model):
    start_date = models.DateTimeField()
    message = models.TextField()
    filters = models.JSONField(default=dict)
    end_date = models.DateTimeField(null=True, blank=True)
    time_interval_start = models.TimeField(default=DAY_START_TIME)
    time_interval_end = models.TimeField(default=DAY_END_TIME)

    class Meta:
        db_table = 'mailing'
        indexes = [
            models.Index(fields=['start_date'])
        ]


class MailingTask(models.Model):
    mailing = models.OneToOneField(Mailing, on_delete=models.CASCADE, related_name='mailing_task', primary_key=True)
    task = models.CharField(max_length=255)

    class Meta:
        db_table = 'mailing_task'


class Message(models.Model):
    create_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=255)
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, related_name='messages')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='messages')

    class Meta:
        db_table = 'message'
        indexes = [
            models.Index(fields=['status'])
        ]

mailing/forms.py
from django import forms

from .models import Mailing
from .validators import MailingValidator


class MailingForm(forms.ModelForm):
    filters = forms.JSONField(required=False, initial=dict)

    validator = MailingValidator()

    class Meta:
        model = Mailing
        fields = ('start_date', 'message', 'filters', 'end_date', 'time_interval_start', 'time_interval_end')
        labels = {
            'start_date': 'Дата начала исполнения',
            'message': 'Сообщение',
            'filters': 'Условия выборки клиентов',
            'end_date': 'Дата окончания рассылки',
            'time_interval_start': 'Начало временного интервала',
            'time_interval_end': 'Конец временного интервала'
        }

    def clean_start_date(self):
        start_date = self.cleaned_data.get('start_date')
        self.validator.validate_start_date(start_date)
        return start_date

    def clean_message(self):
        message = self.cleaned_data.get('message')
        self.validator.validate_message(message)
        return message

    def clean_filters(self):
        filters = self.cleaned_data.get('filters')
        self.validator.validate_filters(filters)
        return filters

    def clean_end_date(self):
        end_date = self.cleaned_data.get('end_date')
        self.validator.validate_end_date(end_date)
        return end_date

    def clean_time_interval_start(self):
        time_interval_start = self.cleaned_data.get('time_interval_start')
        self.validator.validate_time_interval_start(time_interval_start)
        return time_interval_start

    def clean_time_interval_end(self):
        time_interval_end = self.cleaned_data.get('time_interval_end')
        self.validator.validate_time_interval_end(time_interval_end)
        return time_interval_end

    def clean(self):
        self.validator.validate(**self.cleaned_data)
        return super().clean()

web_ui/forms.py
from mailing.forms import MailingForm as BaseMailingFrom
from .widgets import DateTimeWidget, TimeWidget


class MailingFrom(BaseMailingFrom):
    class Meta(BaseMailingFrom.Meta):
        widgets = {
            'start_date': DateTimeWidget(),
            'end_date': DateTimeWidget(),
            'time_interval_start': TimeWidget(),
            'time_interval_end': TimeWidget()
        }

web_ui/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from mailing.logic.mailing_report.services import MailingReporter
from mailing.repository import MailingRepository
from .forms import MailingFrom


class MailingsMixin(LoginRequiredMixin):
    pk_url_kwarg = 'mailing_id'
    ordering = 'start_date'
    repo = MailingRepository()

    def get_queryset(self):
        return self.repo.all_mailings()


class MainRedirectView(generic.RedirectView):
    url = reverse_lazy('web_ui:mailings')


class MailingsView(MailingsMixin, generic.ListView):
    template_name = 'web_ui/mailings.html'


class MailingView(MailingsMixin, generic.DetailView):
    template_name = 'web_ui/mailing.html'


class MailingCreateView(MailingsMixin, generic.CreateView):
    template_name = 'web_ui/mailing_form.html'
    form_class = MailingFrom


class MailingUpdateView(MailingsMixin, generic.UpdateView):
    template_name = 'web_ui/mailing_form.html'
    form_class = MailingFrom

    def get_success_url(self):
        return reverse_lazy('web_ui:mailing', kwargs={'mailing_id': self.object.pk})


class MailingDeleteView(MailingsMixin, generic.DeleteView):
    template_name = 'web_ui/mailing_form.html'
    success_url = reverse_lazy('web_ui:mailings')


class MailingReportView(MailingsMixin, generic.TemplateView):
    template_name = 'web_ui/mailings_report.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        mailing_id = self.kwargs.get('mailing_id')
        reporter = MailingReporter(self.repo)
        report = reporter.get_report(mailing_id)
        ctx['report'] = report
        return ctx

web_ui/templates/web_ui/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>WEB_UI</title>
    <style>
        body
        {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }
        .nav
        {
            width: 100%;
            height: 50px;
            display: flex;
            flex-direction: row;
            background: #d7d7d7;
        }
        .nav .title
        {
            flex-grow: 1;
            padding: 10px;
        }
        .nav .user
        {
            padding: 10px;
        }
        .container
        {
            margin: 20px;
        }
    </style>
    {% block head %}

    {% endblock %}
</head>
<body>
    <div class="nav">
        <div class="title">F R</div>
        {% if user.is_authenticated %}
            <div class="user">
                <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16"><path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/><path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/></svg>
                <b>{{ user.username }}</b>
                <a href={% url 'web_ui:logout' %}>Выйти</a>
            </div>
        {% endif %}
    </div>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

web_ui/templates/web_ui/mailing.html
{% extends 'web_ui/base.html' %}
{% load tags %}



{% block content %}
    <h1 class="title">Подробная информация по рассылке №{{ object.pk }}</h1>
    <table class="mailing">
        <tr>
            <th class="start_date">Дата старта</th>
            <td class="start_date">{{ object.start_date }}</td>
        </tr>
        <tr>
            <th class="message">Сообщение</th>
            <td class="message">{{ object.message }}</td>
        </tr>
        <tr>
            <th class="filters">Фильтр клиентов</th>
            <td class="filters">{{ object.filters }}</td>
        </tr>
        <tr>
            <th class="end_date">Дата принудительного завершения</th>
            <td class="end_date">{{ object.end_date }}</td>
        </tr>
        <tr>
            <th class="time_interval_start">Старт интервала времени приема сообщения</th>
            <td class="time_interval_start">{{ object.time_interval_start }}</td>
        </tr>
        <tr>
            <th class="time_interval_end">Конец интервала времени приема сообщения</th>
            <td class="time_interval_end">{{ object.time_interval_end }}</td>
        </tr>
    </table>
    <div class="control">
        <a href="{% url 'web_ui:mailings' %}"><button>Вернуться</button></a>
        <a href="{% url 'web_ui:mailing_report' mailing_id=object.pk %}"><button {% if not object.start_date|date_has_expired %}disabled{% endif %}>Отчет</button></a>
        <a href="{% url 'web_ui:mailing_update' mailing_id=object.pk %}"><button {% if object.start_date|date_has_expired %}disabled{% endif %}>Обновить</button></a>
        <a href="{% url 'web_ui:mailing_delete' mailing_id=object.pk %}"><button>Удалить</button></a>
    </div>
{% endblock %}


{% block head %}
    <style>
        table.mailing, .mailing td, .mailing th
        {
            border: 1px solid black;
        }
        .mailing tr
        {
            height: 50px;
        }
        .mailing th
        {
            padding: 0 50px 0 20px;
            text-align: start;
        }
        .mailing td
        {
            padding: 0 50px;
        }
    </style>
{% endblock %}

web_ui/templates/web_ui/mailing_form.html
{% extends 'web_ui/base.html' %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit">Подтвердить</button>
        <a
                {% if object %}
                    href="{% url 'web_ui:mailing' mailing_id=object.pk %}"
                {% else %}
                    href="{% url 'web_ui:mailings' %}"
                {% endif %}
        >
            <button type="button">Отменить</button>
        </a>
    </form>
{% endblock %}

web_ui/templates/web_ui/mailings.html
{% extends 'web_ui/base.html' %}


{% block content %}
    <div class="control">
        <a href={% url 'web_ui:mailing_create' %}><button>Создать рассылку</button></a>
        <a href={% url 'web_ui:mailings_report' %}><button>Отчет по всем рассылкам</button></a>
    </div>
    <table class="mailings">
        <thead>
            <tr>
                <th class="mailing_id">Номер</th>
                <th class="start_date">Дата старта</th>
                <th class="message">Сообщение</th>
                <th class="filters">Фильтр клиентов</th>
                <th class="end_date">Дата принудительного завершения</th>
                <th class="time_interval_start">Старт интервала времени приема сообщения</th>
                <th class="time_interval_end">Конец интервала времени приема сообщения</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
                <tr onclick="window.location.href = `{% url 'web_ui:mailing' mailing_id=object.pk %}`">
                    <td class="mailing_id">{{ object.pk }}</td>
                    <td class="start_date">{{ object.start_date }}</td>
                    <td class="message">{{ object.message }}</td>
                    <td class="filters">{{ object.filters }}</td>
                    <td class="end_date">{{ object.end_date }}</td>
                    <td class="time_interval_start">{{ object.time_interval_start }}</td>
                    <td class="time_interval_end">{{ object.time_interval_end }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}


{% block head %}
    <style>
        .mailings
        {
            width: 100%;
        }
        table.mailings, .mailings td, .mailings th
        {
            border: 1px solid black;
        }
        .mailings thead
        {
            position: sticky;
            top: 0;
        }
        .mailings th
        {
            border: 1px solid black;
            background: white;
            font-size: 1.2em;
            padding: 10px;
        }
        .mailings tbody tr
        {
            height: 50px;
        }
        .mailings tbody tr:hover
        {
            background: #000000;
            color: white;
            transition: 0.5s;
            cursor: pointer;
        }

    </style>
{% endblock %}

web_ui/templates/web_ui/mailings_report.html
{% extends 'web_ui/base.html' %}


{% block content %}
    {% if mailing_id %}
        <h1>Отчет по рассылке №{{ mailing_id }}</h1>
    {% else %}
        <h1>Общий отчет по рассылкам</h1>
    {% endif %}

    <table class="statuses">
        <thead>
            <tr>
                <th>Статус</th>
                <th>Количество</th>
            </tr>
        </thead>
        <tbody>
            {% for item in report %}
                <tr class="item">
                    <td>{{ item.status }}</td>
                    <td>{{ item.message_count }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="control">
        <a
                {% if mailing_id %}
                    href="{% url 'web_ui:mailing' mailing_id=mailing_id %}"
                {% else %}
                    href="{% url 'web_ui:mailings' %}"
                {% endif %}
        >
            <button>Вернуться</button>
        </a>
    </div>
{% endblock %}


{% block head %}
    <style>
        table.statuses, .statuses td, .statuses th
        {
            border: 1px solid black;
        }
        .statuses thead
        {
            position: sticky;
            top: 0;
        }
        .statuses tbody tr
        {
            height: 50px;
        }
        .statuses th
        {
            border: 1px solid black;
            background: white;
            font-size: 1.2em;
            padding: 10px;
        }

    </style>
{% endblock %}